---
name: Build puppet-runtime

permissions:
  contents: read # minimal required permissions to clone repo

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag to build'
        required: true
      project_name:
        description: 'The vanagon project to build'
        required: false
        default: 'agent-runtime-main'
      platform_list:
        description: 'A comma-separated list of platforms to build for. Do not include spaces. If not provided, will use the default list of platform supported by OpenVox.'
        required: false
        type: string
      vanagon_branch:
        description: 'The branch of the vanagon repository to use'
        required: false
        type: string
        default: 'main'
      upload_to_s3:
        description: 'Whether to upload the built artifacts to S3. If false, the artifacts will only be uploaded as workflow artifacts.'
        required: false
        type: boolean
        default: true
      use_dev:
        description: 'Use the "dev" branch of the shared-actions repo'
        required: false
        type: boolean
        default: false

jobs:
  build:
    if: ${{ github.event.inputs.use_dev == 'false' }}
    uses: 'openvoxproject/shared-actions/.github/workflows/build_vanagon.yml@main'
    with:
      ref: ${{ inputs.ref }}
      project_name: ${{ inputs.project_name }}
      platform_list: ${{ inputs.platform_list }}
      vanagon_branch: ${{ inputs.vanagon_branch }}
      #upload_to_s3: ${{ inputs.upload_to_s3 }}
    secrets: inherit
  build_dev:
    if: ${{ github.event.inputs.use_dev == 'true' }}
    uses: 'openvoxproject/shared-actions/.github/workflows/build_vanagon.yml@dev'
    with:
      ref: ${{ inputs.ref }}
      project_name: ${{ inputs.project_name }}
      platform_list: ${{ inputs.platform_list }}
      vanagon_branch: ${{ inputs.vanagon_branch }}
      upload_to_s3: ${{ inputs.upload_to_s3 }}
    secrets: inherit
