---
name: Runtime tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  BUNDLE_WITHOUT: development

jobs:
  vanagon_inspect:
    name: Vanagon inspect
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Ruby version 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Vanagon inspect
        run: |
          stat=0
          for projfile in configs/projects/[a-z]*.rb; do
            for plat in el-7-x86_64 ubuntu-18.04-amd64 ubuntu-20.04-amd64 ubuntu-22.04-amd64 windows-2012r2-x64; do
              proj=$(basename -s .rb "$projfile")
              if [[ "$proj" =~ ^pe- && "$plat" =~ ^(windows|osx) ]]; then
                echo Skipping ${proj} on ${plat}, PE projects don\'t support Windows or macOS
                continue
              fi
              echo Inspecting ${proj} on ${plat}
              output=$(bundle exec vanagon inspect "$proj" "$plat")
              if [ $? -ne 0 ]; then
                stat=1
              else
                echo "$output" | jq '.[].name'
              fi
            done
          done
          # fail this step if there were any failures
          if [ $stat -eq 1 ]; then
            false
          fi
